/* Fish of the Day — Shared Dataset
   Each entry: [common name, Genus, species, Family, Order,
                max length cm, habitat, depth range, pre-baked image URL?] */
const FISH = [
  ["Clown Anemonefish","Amphiprion","ocellaris","Pomacentridae","Perciformes",11,"Marine","1–15 m","https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Clown_fish_in_the_Andaman_Coral_Reef.jpg/480px-Clown_fish_in_the_Andaman_Coral_Reef.jpg"],
  ["Blue Tang","Paracanthurus","hepatus","Acanthuridae","Perciformes",31,"Marine","2–40 m","https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Paletten-Doktorfisch_M%C3%BCnster.JPG/480px-Paletten-Doktorfisch_M%C3%BCnster.JPG"],
  ["Atlantic Salmon","Salmo","salar","Salmonidae","Salmoniformes",150,"Freshwater, Marine","0–210 m","https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Wst_atlantischer_lachs_stoer_001.jpg/480px-Wst_atlantischer_lachs_stoer_001.jpg"],
  ["Rainbow Trout","Oncorhynchus","mykiss","Salmonidae","Salmoniformes",120,"Freshwater","0–200 m","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Close_up_of_rainbow_trout_fish_underwater_oncorhynchus_mykiss.jpg/480px-Close_up_of_rainbow_trout_fish_underwater_oncorhynchus_mykiss.jpg"],
  ["Common Carp","Cyprinus","carpio","Cyprinidae","Cypriniformes",120,"Freshwater","0–30 m","https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Cyprinus_carpio_2008_G1_%28cropped%29.jpg/480px-Cyprinus_carpio_2008_G1_%28cropped%29.jpg"],
  ["Goldfish","Carassius","auratus","Cyprinidae","Cypriniformes",41,"Freshwater","0–20 m","https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Gold_fish1.jpg/480px-Gold_fish1.jpg"],
  ["Siamese Fighting Fish","Betta","splendens","Osphronemidae","Anabantiformes",7,"Freshwater","0–1 m","https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/HM_Orange_M_Sarawut.jpg/480px-HM_Orange_M_Sarawut.jpg"],
  ["Northern Pike","Esox","lucius","Esocidae","Esociformes",150,"Freshwater","0–30 m","https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Esox_lucius_ZOO_1.jpg/480px-Esox_lucius_ZOO_1.jpg"],
  ["Largemouth Bass","Micropterus","salmoides","Centrarchidae","Perciformes",97,"Freshwater","0–20 m","https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Largemouth_Bass_%28Micropterus_salmoides%29_June_2023_%28cropped%29.jpg/480px-Largemouth_Bass_%28Micropterus_salmoides%29_June_2023_%28cropped%29.jpg"],
  ["European Perch","Perca","fluviatilis","Percidae","Perciformes",60,"Freshwater","1–30 m","https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Barsche_im_See_%28Jungfische%29.jpg/480px-Barsche_im_See_%28Jungfische%29.jpg"],
  ["Whale Shark","Rhincodon","typus","Rhincodontidae","Orectolobiformes",1200,"Marine","0–1928 m","https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Similan_Dive_Center_-_great_whale_shark.jpg/480px-Similan_Dive_Center_-_great_whale_shark.jpg"],
  ["Great White Shark","Carcharodon","carcharias","Lamnidae","Lamniformes",600,"Marine","0–1200 m","https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/White_shark.jpg/480px-White_shark.jpg"],
  ["Ocean Sunfish","Mola","mola","Molidae","Tetraodontiformes",333,"Marine","30–480 m","https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Mola_mola.jpg/480px-Mola_mola.jpg"],
  ["Atlantic Bluefin Tuna","Thunnus","thynnus","Scombridae","Scombriformes",458,"Marine","0–1000 m","https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Bluefin-big.jpg/480px-Bluefin-big.jpg"],
  ["Yellowfin Tuna","Thunnus","albacares","Scombridae","Scombriformes",239,"Marine","1–250 m","https://upload.wikimedia.org/wikipedia/commons/c/c3/Thunnus_albacares.png"],
  ["Atlantic Cod","Gadus","morhua","Gadidae","Gadiformes",200,"Marine","0–600 m","https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Atlantic_Cod%2C_Atlantischer_Kabeljau_%28Gadus_morhua%29.jpg/480px-Atlantic_Cod%2C_Atlantischer_Kabeljau_%28Gadus_morhua%29.jpg"],
  ["Spotted Seahorse","Hippocampus","kuda","Syngnathidae","Syngnathiformes",17,"Marine","0–55 m","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Hal_-_Hippocampus_kuda_-_4.jpg/480px-Hal_-_Hippocampus_kuda_-_4.jpg"],
  ["Red Lionfish","Pterois","volitans","Scorpaenidae","Scorpaeniformes",38,"Marine","2–55 m","https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Pterois_volitans_Manado-e_edit.jpg/480px-Pterois_volitans_Manado-e_edit.jpg"],
  ["Mandarinfish","Synchiropus","splendidus","Callionymidae","Perciformes",6,"Marine","1–18 m","https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Synchiropus_splendidus_2_Luc_Viatour.jpg/480px-Synchiropus_splendidus_2_Luc_Viatour.jpg"],
  ["Atlantic Mackerel","Scomber","scombrus","Scombridae","Scombriformes",60,"Marine","0–300 m","https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Scomber_scombrus_217326414.jpg/480px-Scomber_scombrus_217326414.jpg"],
  ["European Eel","Anguilla","anguilla","Anguillidae","Anguilliformes",133,"Freshwater, Marine","0–700 m","https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Anguilla_anguilla.jpg/480px-Anguilla_anguilla.jpg"],
  ["Giant Manta Ray","Mobula","birostris","Mobulidae","Myliobatiformes",910,"Marine","0–120 m","https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Manta_birostris-Thailand4.jpg/480px-Manta_birostris-Thailand4.jpg"],
  ["Sockeye Salmon","Oncorhynchus","nerka","Salmonidae","Salmoniformes",84,"Freshwater, Marine","0–250 m","https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Sockeye_salmon_swimming_right.jpg/480px-Sockeye_salmon_swimming_right.jpg"],
  ["Moorish Idol","Zanclus","cornutus","Zanclidae","Perciformes",23,"Marine","3–182 m","https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/%C3%8Ddolo_moro_%28Zanclus_cornutus%29%2C_Anilao%2C_Filipinas%2C_2023-08-25%2C_DD_233.jpg/480px-%C3%8Ddolo_moro_%28Zanclus_cornutus%29%2C_Anilao%2C_Filipinas%2C_2023-08-25%2C_DD_233.jpg"],
  ["Atlantic Herring","Clupea","harengus","Clupeidae","Clupeiformes",45,"Marine","0–364 m","https://upload.wikimedia.org/wikipedia/commons/0/04/Clupea_harengus.png"],
  ["Zebrafish","Danio","rerio","Cyprinidae","Cypriniformes",4,"Freshwater","surface","https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Zebrafisch.jpg/480px-Zebrafisch.jpg"],
  ["Nile Tilapia","Oreochromis","niloticus","Cichlidae","Cichliformes",60,"Freshwater","0–20 m","https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Til%C3%A1pia_ou_Sarotherodon_niloticus_2.jpg/480px-Til%C3%A1pia_ou_Sarotherodon_niloticus_2.jpg"],
  ["Atlantic Halibut","Hippoglossus","hippoglossus","Pleuronectidae","Pleuronectiformes",470,"Marine","0–2000 m","https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Hippoglossus_hippoglossus_196509307.jpg/480px-Hippoglossus_hippoglossus_196509307.jpg"],
  ["Humphead Wrasse","Cheilinus","undulatus","Labridae","Perciformes",229,"Marine","1–100 m","https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Humphead_wrasse_melb_aquarium.jpg/480px-Humphead_wrasse_melb_aquarium.jpg"],
  ["Pufferfish","Tetraodon","nigroviridis","Tetraodontidae","Tetraodontiformes",17,"Freshwater, Brackish","surface","https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Dichotomyctere_nigroviridis_Natural_History_Museum_University_of_Pisa_%28cropped%29.jpg/480px-Dichotomyctere_nigroviridis_Natural_History_Museum_University_of_Pisa_%28cropped%29.jpg"],
  ["Striped Bass","Morone","saxatilis","Moronidae","Perciformes",200,"Freshwater, Marine","0–30 m","https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Morone_saxatilis_SI2.jpg/480px-Morone_saxatilis_SI2.jpg"],
  ["Bluegill","Lepomis","macrochirus","Centrarchidae","Perciformes",41,"Freshwater","0–16 m","https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Bluegill_%28cropped%29.jpg/480px-Bluegill_%28cropped%29.jpg"],
  ["King Mackerel","Scomberomorus","cavalla","Scombridae","Scombriformes",184,"Marine","5–40 m","https://upload.wikimedia.org/wikipedia/commons/4/40/Scomberomorus_cavalla.png"],
  ["Yellow Perch","Perca","flavescens","Percidae","Perciformes",50,"Freshwater","0–15 m","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Yellow_Perch_%28Perca_flavescens%29_%28cropped%29.jpg/480px-Yellow_Perch_%28Perca_flavescens%29_%28cropped%29.jpg"],
  ["Mahi-mahi","Coryphaena","hippurus","Coryphaenidae","Perciformes",210,"Marine","0–85 m","https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Coryphaenahippurus.JPG/480px-Coryphaenahippurus.JPG"],
  ["Swordfish","Xiphias","gladius","Xiphiidae","Istiophoriformes",455,"Marine","0–800 m","https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Xiphias_gladius_Linnaeus%2C_1758_2599925021.jpg/480px-Xiphias_gladius_Linnaeus%2C_1758_2599925021.jpg"],
  ["Common Sole","Solea","solea","Soleidae","Pleuronectiformes",70,"Marine","0–150 m","https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Solea_solea_1.jpg/480px-Solea_solea_1.jpg"],
  ["Walleye","Sander","vitreus","Percidae","Perciformes",107,"Freshwater","0–30 m","https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Walleye_%28Sander_vitreus%29_%281%29.jpg/480px-Walleye_%28Sander_vitreus%29_%281%29.jpg"],
  ["Pumpkinseed","Lepomis","gibbosus","Centrarchidae","Perciformes",40,"Freshwater","0–12 m","https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Lepomis_adult.jpg/480px-Lepomis_adult.jpg"],
  ["Tiger Barb","Puntigrus","tetrazona","Cyprinidae","Cypriniformes",7,"Freshwater","surface","https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Tiger_barb_fish.jpg/480px-Tiger_barb_fish.jpg"],
  ["Oscar","Astronotus","ocellatus","Cichlidae","Cichliformes",45,"Freshwater","0–2 m","https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Astronotus_ocellatus.jpg/480px-Astronotus_ocellatus.jpg"],
  ["Discus","Symphysodon","discus","Cichlidae","Cichliformes",20,"Freshwater","1–4 m","https://upload.wikimedia.org/wikipedia/commons/b/b6/Discus_heckel.jpg"],
  ["Guppy","Poecilia","reticulata","Poeciliidae","Cyprinodontiformes",5,"Freshwater","surface","https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Guppy_pho_0048.jpg/480px-Guppy_pho_0048.jpg"],
  ["Neon Tetra","Paracheirodon","innesi","Characidae","Characiformes",4,"Freshwater","surface","https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Neonsalmler_Paracheirodon_innesi.jpg/480px-Neonsalmler_Paracheirodon_innesi.jpg"],
  ["Piranha","Pygocentrus","nattereri","Serrasalmidae","Characiformes",33,"Freshwater","0–5 m","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Pygocentrus_nattereri_-_Karlsruhe_Zoo_01.jpg/480px-Pygocentrus_nattereri_-_Karlsruhe_Zoo_01.jpg"],
  ["Electric Eel","Electrophorus","electricus","Gymnotidae","Gymnotiformes",250,"Freshwater","surface","https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Electric-eel.jpg/480px-Electric-eel.jpg"],
  ["Arapaima","Arapaima","gigas","Arapaimidae","Osteoglossiformes",450,"Freshwater","surface","https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Arapaima_gigas_at_Beijing_aquarium.JPG/480px-Arapaima_gigas_at_Beijing_aquarium.JPG"],
  ["Tiger Shark","Galeocerdo","cuvier","Carcharhinidae","Carcharhiniformes",550,"Marine","0–371 m","https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Tiger_shark.jpg/480px-Tiger_shark.jpg"],
  ["Hammerhead Shark","Sphyrna","mokarran","Sphyrnidae","Carcharhiniformes",610,"Marine","1–300 m","https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Great_hammerhead2.jpg/480px-Great_hammerhead2.jpg"],
  ["Basking Shark","Cetorhinus","maximus","Cetorhinidae","Lamniformes",1520,"Marine","0–2000 m","https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Cetorhinus_maximus_by_greg_skomal.JPG/480px-Cetorhinus_maximus_by_greg_skomal.JPG"],
  ["Blue Marlin","Makaira","nigricans","Istiophoridae","Istiophoriformes",500,"Marine","0–1000 m","https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Atlantic_blue_marlin.jpg/480px-Atlantic_blue_marlin.jpg"],
  ["Sailfish","Istiophorus","platypterus","Istiophoridae","Istiophoriformes",315,"Marine","0–200 m","https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Istiophorus_platypterus_101956558.jpg/480px-Istiophorus_platypterus_101956558.jpg"],
  ["Barramundi","Lates","calcarifer","Latidae","Perciformes",200,"Freshwater, Marine","10–40 m","https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Lates_calcarifer%2C_2014-09-19a.jpg/480px-Lates_calcarifer%2C_2014-09-19a.jpg"],
  ["Peacock Bass","Cichla","ocellaris","Cichlidae","Cichliformes",74,"Freshwater","0–5 m","https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Cichla_ocellaris_Dvur_zoo_1.jpg/480px-Cichla_ocellaris_Dvur_zoo_1.jpg"],
  ["Angelfish","Pterophyllum","scalare","Cichlidae","Cichliformes",15,"Freshwater","0–3 m","https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Pterophyllum_scalare_Natural_History_Museum_University_of_Pisa.jpg/480px-Pterophyllum_scalare_Natural_History_Museum_University_of_Pisa.jpg"],
  ["Clown Triggerfish","Balistoides","conspicillum","Balistidae","Tetraodontiformes",50,"Marine","1–75 m","https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Balistoides_conspicillum_2607.jpg/480px-Balistoides_conspicillum_2607.jpg"],
  ["Royal Gramma","Gramma","loreto","Grammatidae","Perciformes",8,"Marine","1–60 m","https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Gramma_loreto%2C_Adult_%28Royal_Gramma%29.jpg/480px-Gramma_loreto%2C_Adult_%28Royal_Gramma%29.jpg"],
  ["Flame Angelfish","Centropyge","loricula","Pomacanthidae","Perciformes",10,"Marine","15–60 m","https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flame_angelfish_%28Centropyge_loricula%29.jpg/480px-Flame_angelfish_%28Centropyge_loricula%29.jpg"],
  ["Powder Blue Tang","Acanthurus","leucosternon","Acanthuridae","Perciformes",23,"Marine","0–25 m","https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Pez_cirujano_azul_cielo_%28Acanthurus_leucosternon%29%2C_Zanz%C3%ADbar%2C_Tanzania%2C_2024-05-30%2C_DD_80.jpg/480px-Pez_cirujano_azul_cielo_%28Acanthurus_leucosternon%29%2C_Zanz%C3%ADbar%2C_Tanzania%2C_2024-05-30%2C_DD_80.jpg"],
  ["Emperor Angelfish","Pomacanthus","imperator","Pomacanthidae","Perciformes",40,"Marine","1–100 m","https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Emperor_Angelfish%2C_Western_form_-_Pomacanthus_imperator_1.jpg/480px-Emperor_Angelfish%2C_Western_form_-_Pomacanthus_imperator_1.jpg"],
  ["Copperband Butterflyfish","Chelmon","rostratus","Chaetodontidae","Perciformes",20,"Marine","1–25 m","https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Chelmon_rostratus_Luc_Viatour.jpg/480px-Chelmon_rostratus_Luc_Viatour.jpg"],
  ["Yellowtail Snapper","Ocyurus","chrysurus","Lutjanidae","Perciformes",86,"Marine","0–180 m","https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Yellowtail_snapper_seen_from_Underwater_Tunnel_Atlantis.jpg/480px-Yellowtail_snapper_seen_from_Underwater_Tunnel_Atlantis.jpg"],
  ["Red Snapper","Lutjanus","campechanus","Lutjanidae","Perciformes",100,"Marine","10–190 m","https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Red_Snapper.jpg/480px-Red_Snapper.jpg"],
  ["Grouper","Epinephelus","marginatus","Serranidae","Perciformes",150,"Marine","8–300 m","https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Mero_%28Epinephelus_marginatus%29%2C_Cabo_de_Palos%2C_Espa%C3%B1a%2C_2022-07-15%2C_DD_34.jpg/480px-Mero_%28Epinephelus_marginatus%29%2C_Cabo_de_Palos%2C_Espa%C3%B1a%2C_2022-07-15%2C_DD_34.jpg"],
  ["Giant Trevally","Caranx","ignobilis","Carangidae","Carangiformes",170,"Marine","0–100 m","https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Caranx_ignobilis.jpg/480px-Caranx_ignobilis.jpg"],
  ["Permit","Trachinotus","falcatus","Carangidae","Carangiformes",114,"Marine","0–35 m","https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Trachinotus_falcatus.jpg/480px-Trachinotus_falcatus.jpg"],
  ["Bonefish","Albula","vulpes","Albulidae","Albuliformes",104,"Marine","0–84 m","https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Bonefish_Albula_vulpes.jpg/480px-Bonefish_Albula_vulpes.jpg"],
  ["Tarpon","Megalops","atlanticus","Megalopidae","Elopiformes",250,"Marine, Brackish","0–30 m","https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Megalops_atlanticus.jpg/480px-Megalops_atlanticus.jpg"],
  ["Coelacanth","Latimeria","chalumnae","Latimeriidae","Coelacanthiformes",200,"Marine","150–700 m","https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Coelacanth_off_Pumula_on_the_KwaZulu-Natal_South_Coast%2C_South_Africa%2C_on_22_November_2019.png/480px-Coelacanth_off_Pumula_on_the_KwaZulu-Natal_South_Coast%2C_South_Africa%2C_on_22_November_2019.png"],
  ["Spotted Garden Eel","Heteroconger","hassi","Congridae","Anguilliformes",40,"Marine","7–45 m","https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/R%C3%B6r%C3%A5lar.jpg/480px-R%C3%B6r%C3%A5lar.jpg"],
  ["Leafy Seadragon","Phycodurus","eques","Syngnathidae","Syngnathiformes",35,"Marine","3–50 m","https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Leafy_Seadragon_on_Kangaroo_Island.jpg/480px-Leafy_Seadragon_on_Kangaroo_Island.jpg"],
  ["Weedy Seadragon","Phyllopteryx","taeniolatus","Syngnathidae","Syngnathiformes",46,"Marine","3–50 m","https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Phyllopteryx_taeniolatus1.jpg/480px-Phyllopteryx_taeniolatus1.jpg"],
  ["Flying Fish","Exocoetus","volitans","Exocoetidae","Beloniformes",30,"Marine","0–20 m","https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Exvol_u0.gif/480px-Exvol_u0.gif"],
  ["Atlantic Mudskipper","Periophthalmus","barbarus","Oxudercidae","Gobiiformes",16,"Brackish","0–2 m","https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/GambianMudskippers.jpg/480px-GambianMudskippers.jpg"],
  ["Archerfish","Toxotes","jaculatrix","Toxotidae","Perciformes",27,"Freshwater, Brackish","surface","https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Toxotes_jaculatrix.jpg/480px-Toxotes_jaculatrix.jpg"],
  ["Parrotfish","Scarus","vetula","Scaridae","Perciformes",61,"Marine","3–25 m","https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Scarus_vetula.jpg/480px-Scarus_vetula.jpg"],
  ["Cleaner Wrasse","Labroides","dimidiatus","Labridae","Perciformes",14,"Marine","1–40 m","https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/L%C3%A1brido_limpiador_com%C3%BAn_%28Labroides_dimidiatus%29%2C_mar_Rojo%2C_Egipto%2C_2023-04-17%2C_DD_90.jpg/480px-L%C3%A1brido_limpiador_com%C3%BAn_%28Labroides_dimidiatus%29%2C_mar_Rojo%2C_Egipto%2C_2023-04-17%2C_DD_90.jpg"],
  ["Yellowtail Amberjack","Seriola","lalandi","Carangidae","Carangiformes",250,"Marine","3–825 m","https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Yellowtail_amberjack.jpg/480px-Yellowtail_amberjack.jpg"],
  ["Red Drum","Sciaenops","ocellatus","Sciaenidae","Perciformes",155,"Marine, Brackish","0–40 m","https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Redfish_or_Red_drum.webp/480px-Redfish_or_Red_drum.webp.png"],
  ["Spotted Trunkfish","Lactophrys","bicaudalis","Ostraciidae","Tetraodontiformes",48,"Marine","3–80 m","https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Spotted_Trunkfish.jpg/480px-Spotted_Trunkfish.jpg"],
  ["Longhorn Cowfish","Lactoria","cornuta","Ostraciidae","Tetraodontiformes",46,"Marine","1–100 m","https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Lactoria_cornuta.004_-_Aquarium_Finisterrae.JPG/480px-Lactoria_cornuta.004_-_Aquarium_Finisterrae.JPG"],
  ["Porcupinefish","Diodon","hystrix","Diodontidae","Tetraodontiformes",91,"Marine","2–50 m","https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pez_erizo_moteado_%28Diodon_hystrix%29%2C_Cabo_Pulmo%2C_Baja_California%2C_M%C3%A9xico%2C_2024-12-19%2C_DD_23.jpg/480px-Pez_erizo_moteado_%28Diodon_hystrix%29%2C_Cabo_Pulmo%2C_Baja_California%2C_M%C3%A9xico%2C_2024-12-19%2C_DD_23.jpg"],
  ["Atlantic Wolffish","Anarhichas","lupus","Anarhichadidae","Perciformes",150,"Marine","1–500 m","https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Anarhichas-lupus-Atlanterhavsparken.jpg/480px-Anarhichas-lupus-Atlanterhavsparken.jpg"],
  ["Stoplight Parrotfish","Sparisoma","viride","Scaridae","Perciformes",64,"Marine","3–50 m","https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Stoplight-parrotfish.jpg/480px-Stoplight-parrotfish.jpg"],
  ["Bicolor Parrotfish","Cetoscarus","bicolor","Scaridae","Perciformes",90,"Marine","1–30 m","https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Cetoscarus_bicolor_by_Jacek_Madejski.jpg/480px-Cetoscarus_bicolor_by_Jacek_Madejski.jpg"],
  ["Harlequin Tuskfish","Choerodon","fasciatus","Labridae","Perciformes",25,"Marine","1–25 m","https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Choerodon_fasciatus.jpg/480px-Choerodon_fasciatus.jpg"],
  ["Foxface Rabbitfish","Siganus","vulpinus","Siganidae","Perciformes",24,"Marine","1–30 m","https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Siganus_vulpinus_2.jpg/480px-Siganus_vulpinus_2.jpg"],
  ["Picasso Triggerfish","Rhinecanthus","aculeatus","Balistidae","Tetraodontiformes",30,"Marine","0–4 m","https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Picasso.triggerfish.arp.jpg/480px-Picasso.triggerfish.arp.jpg"],
  ["Pacific Blue Tang","Acanthurus","coeruleus","Acanthuridae","Perciformes",39,"Marine","2–40 m","https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Acanthurus_coeruleus_-_Sanc1516.jpg/480px-Acanthurus_coeruleus_-_Sanc1516.jpg"],
  ["French Angelfish","Pomacanthus","paru","Pomacanthidae","Perciformes",41,"Marine","2–100 m","https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Beauty_and_Brains_%288457803488%29.jpg/480px-Beauty_and_Brains_%288457803488%29.jpg"],
  ["Queen Angelfish","Holacanthus","ciliaris","Pomacanthidae","Perciformes",45,"Marine","1–70 m","https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Queen_Angelfish.jpg/480px-Queen_Angelfish.jpg"],
  ["Sergeant Major","Abudefduf","saxatilis","Pomacentridae","Perciformes",23,"Marine","0–15 m","https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/SergeantMajor_Icon.jpg/480px-SergeantMajor_Icon.jpg"],
  ["Garibaldi","Hypsypops","rubicundus","Pomacentridae","Perciformes",36,"Marine","1–30 m","https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Hypsypops_rubicundus_adult.jpg/480px-Hypsypops_rubicundus_adult.jpg"],
  ["Tench","Tinca","tinca","Cyprinidae","Cypriniformes",84,"Freshwater","1–12 m","https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Tinca_tinca_Natural_History_Museum_University_of_Pisa.jpg/480px-Tinca_tinca_Natural_History_Museum_University_of_Pisa.jpg"],
  ["Wels Catfish","Silurus","glanis","Siluridae","Siluriformes",500,"Freshwater","2–80 m","https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Silurus_glanis_02.jpg/480px-Silurus_glanis_02.jpg"],
  ["Channel Catfish","Ictalurus","punctatus","Ictaluridae","Siluriformes",132,"Freshwater","0–20 m","https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Channel_Catfish_%28Ictalurus_punctatus%29_white_background.jpg/480px-Channel_Catfish_%28Ictalurus_punctatus%29_white_background.jpg"],
  ["Brook Trout","Salvelinus","fontinalis","Salmonidae","Salmoniformes",86,"Freshwater","0–20 m","https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Brook_trout_in_water.jpg/480px-Brook_trout_in_water.jpg"],
  ["Lake Trout","Salvelinus","namaycush","Salmonidae","Salmoniformes",150,"Freshwater","0–200 m","https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Lake_trout_fishes_salvelinus_namaycush.jpg/480px-Lake_trout_fishes_salvelinus_namaycush.jpg"],
  ["Brown Trout","Salmo","trutta","Salmonidae","Salmoniformes",140,"Freshwater, Marine","0–230 m","https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Brown_Trout_%28Salmo_trutta%29_%2853678765394%29.jpg/480px-Brown_Trout_%28Salmo_trutta%29_%2853678765394%29.jpg"],
  ["Chinook Salmon","Oncorhynchus","tshawytscha","Salmonidae","Salmoniformes",150,"Freshwater, Marine","0–250 m","https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Chinook_Salmon_Adult_Male.jpg/480px-Chinook_Salmon_Adult_Male.jpg"],
  ["Pink Salmon","Oncorhynchus","gorbuscha","Salmonidae","Salmoniformes",76,"Freshwater, Marine","0–250 m","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Humpback_Salmon_Adult_Male.jpg/480px-Humpback_Salmon_Adult_Male.jpg"],
  ["Arctic Char","Salvelinus","alpinus","Salmonidae","Salmoniformes",107,"Freshwater","0–75 m",""],
  ["Atlantic Sturgeon","Acipenser","oxyrinchus","Acipenseridae","Acipenseriformes",460,"Freshwater, Marine","0–48 m","https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Huge_sturgeon_in_the_Gulf_of_St._Lawrence_ecosystem_-_panoramio.jpg/480px-Huge_sturgeon_in_the_Gulf_of_St._Lawrence_ecosystem_-_panoramio.jpg"],
  ["Beluga Sturgeon","Huso","huso","Acipenseridae","Acipenseriformes",600,"Freshwater, Marine","0–180 m","https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/%D0%91%D1%96%D0%BB%D1%83%D0%B3%D0%B0_%28Huso_huso%29.jpg/480px-%D0%91%D1%96%D0%BB%D1%83%D0%B3%D0%B0_%28Huso_huso%29.jpg"],
  ["Paddlefish","Polyodon","spathula","Polyodontidae","Acipenseriformes",221,"Freshwater","0–12 m",""],
  ["Longnose Gar","Lepisosteus","osseus","Lepisosteidae","Lepisosteiformes",200,"Freshwater","0–20 m",""],
  ["Bowfin","Amia","calva","Amiidae","Amiiformes",109,"Freshwater","0–6 m",""],
  ["Alligator Gar","Atractosteus","spatula","Lepisosteidae","Lepisosteiformes",305,"Freshwater","0–14 m",""],
  ["Yellowfin Goby","Acanthogobius","flavimanus","Gobiidae","Gobiiformes",30,"Brackish, Marine","0–20 m","https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Acanthogobius_flavimanus_Nakagawa.jpg/480px-Acanthogobius_flavimanus_Nakagawa.jpg"],
  ["Frogfish","Antennarius","striatus","Antennariidae","Lophiiformes",22,"Marine","10–219 m",""],
  ["Anglerfish","Lophius","piscatorius","Lophiidae","Lophiiformes",200,"Marine","20–1000 m",""],
  ["John Dory","Zeus","faber","Zeidae","Zeiformes",90,"Marine","5–400 m",""],
  ["Opah","Lampris","guttatus","Lampridae","Lampriformes",200,"Marine","0–500 m",""],
  ["Oarfish","Regalecus","glesne","Regalecidae","Lampriformes",1100,"Marine","20–1000 m","https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Cuvier-69-Gymn%C3%A8tre.jpg/480px-Cuvier-69-Gymn%C3%A8tre.jpg"],
  ["Atlantic Flounder","Paralichthys","dentatus","Paralichthyidae","Pleuronectiformes",94,"Marine","0–80 m",""],
  ["Turbot","Scophthalmus","maximus","Scophthalmidae","Pleuronectiformes",100,"Marine","20–70 m","https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Psetta_maxima_Luc_Viatour.jpg/480px-Psetta_maxima_Luc_Viatour.jpg"],
  ["European Plaice","Pleuronectes","platessa","Pleuronectidae","Pleuronectiformes",100,"Marine","0–200 m","https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Pleuronectes_platessa.jpg/480px-Pleuronectes_platessa.jpg"],
  ["Monkfish","Lophius","americanus","Lophiidae","Lophiiformes",120,"Marine","0–668 m",""],
  ["Striped Catfish","Plotosus","lineatus","Plotosidae","Siluriformes",32,"Marine","1–60 m",""],
  ["Cardinal Tetra","Paracheirodon","axelrodi","Characidae","Characiformes",5,"Freshwater","surface",""],
  ["Congo Tetra","Phenacogrammus","interruptus","Alestidae","Characiformes",8,"Freshwater","surface",""],
  ["Silver Arowana","Osteoglossum","bicirrhosum","Osteoglossidae","Osteoglossiformes",120,"Freshwater","surface",""],
  ["Asian Arowana","Scleropages","formosus","Osteoglossidae","Osteoglossiformes",90,"Freshwater","surface",""],
  ["Freshwater Angelfish","Pterophyllum","altum","Cichlidae","Cichliformes",18,"Freshwater","surface",""],
  ["Jack Dempsey","Rocio","octofasciata","Cichlidae","Cichliformes",25,"Freshwater","0–3 m","https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Cichlasoma_octofasciata2.jpg/480px-Cichlasoma_octofasciata2.jpg"],
  ["Convict Cichlid","Amatitlania","nigrofasciata","Cichlidae","Cichliformes",10,"Freshwater","0–3 m",""],
  ["Frontosa Cichlid","Cyphotilapia","frontosa","Cichlidae","Cichliformes",35,"Freshwater","10–70 m",""],
  ["Flowerhorn Cichlid","Amphilophus","trimaculatus","Cichlidae","Cichliformes",35,"Freshwater","0–5 m",""],
  ["Plecostomus","Hypostomus","plecostomus","Loricariidae","Siluriformes",50,"Freshwater","surface",""],
  ["Corydoras Catfish","Corydoras","paleatus","Callichthyidae","Siluriformes",7,"Freshwater","surface",""],
  ["Clown Loach","Chromobotia","macracanthus","Botiidae","Cypriniformes",40,"Freshwater","0–5 m",""],
  ["Cherry Barb","Puntius","titteya","Cyprinidae","Cypriniformes",5,"Freshwater","surface",""],
  ["Hatchetfish","Gasteropelecus","sternicla","Gasteropelecidae","Characiformes",4,"Freshwater","surface",""],
  ["Dwarf Gourami","Trichogaster","lalius","Osphronemidae","Anabantiformes",9,"Freshwater","surface",""],
  ["Pearl Gourami","Trichopodus","leerii","Osphronemidae","Anabantiformes",12,"Freshwater","surface",""],
  ["Giant Gourami","Osphronemus","goramy","Osphronemidae","Anabantiformes",70,"Freshwater","surface","https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Osphronemus_Gourami_%28better%29.png/480px-Osphronemus_Gourami_%28better%29.png"],
  ["Snakehead","Channa","striata","Channidae","Anabantiformes",100,"Freshwater","surface",""],
  ["Red Belly Pacu","Piaractus","brachypomus","Serrasalmidae","Characiformes",88,"Freshwater","0–5 m",""],
  ["Tambaqui","Colossoma","macropomum","Serrasalmidae","Characiformes",108,"Freshwater","0–5 m",""],
  ["Muskellunge","Esox","masquinongy","Esocidae","Esociformes",183,"Freshwater","0–15 m",""],
  ["Smallmouth Bass","Micropterus","dolomieu","Centrarchidae","Perciformes",69,"Freshwater","0–20 m",""],
  ["Black Crappie","Pomoxis","nigromaculatus","Centrarchidae","Perciformes",49,"Freshwater","0–6 m","https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Black_crappie.jpg/480px-Black_crappie.jpg"],
  ["White Sturgeon","Acipenser","transmontanus","Acipenseridae","Acipenseriformes",610,"Freshwater","0–30 m",""],
  ["Cutthroat Trout","Oncorhynchus","clarkii","Salmonidae","Salmoniformes",99,"Freshwater","0‐20 m",""],
  ["Coho Salmon","Oncorhynchus","kisutch","Salmonidae","Salmoniformes",108,"Freshwater, Marine","0–250 m",""],
  ["Grayling","Thymallus","thymallus","Salmonidae","Salmoniformes",60,"Freshwater","0–30 m",""],
  ["Huchen","Hucho","hucho","Salmonidae","Salmoniformes",150,"Freshwater","0–30 m",""],
  ["Zander","Sander","lucioperca","Percidae","Perciformes",130,"Freshwater","1–30 m",""],
  ["Rudd","Scardinius","erythrophthalmus","Cyprinidae","Cypriniformes",51,"Freshwater","0–3 m",""],
  ["Bleak","Alburnus","alburnus","Cyprinidae","Cypriniformes",25,"Freshwater","surface",""],
  ["Barbel","Barbus","barbus","Cyprinidae","Cypriniformes",120,"Freshwater","1–10 m","https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Barbel.jpg/480px-Barbel.jpg"],
  ["Stone Loach","Barbatula","barbatula","Nemacheilidae","Cypriniformes",21,"Freshwater","surface",""],
  ["Weather Loach","Misgurnus","fossilis","Cobitidae","Cypriniformes",30,"Freshwater","surface",""],
  ["Spiny Dogfish","Squalus","acanthias","Squalidae","Squaliformes",160,"Marine","0–900 m",""],
  ["Nurse Shark","Ginglymostoma","cirratum","Ginglymostomatidae","Orectolobiformes",430,"Marine","0–130 m",""],
  ["Lemon Shark","Negaprion","brevirostris","Carcharhinidae","Carcharhiniformes",340,"Marine","0–92 m",""],
  ["Bull Shark","Carcharhinus","leucas","Carcharhinidae","Carcharhiniformes",340,"Marine, Freshwater","0–150 m","https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Bull_shark_size.svg/480px-Bull_shark_size.svg.png"],
  ["Blue Shark","Prionace","glauca","Carcharhinidae","Carcharhiniformes",383,"Marine","0–350 m",""],
  ["Mako Shark","Isurus","oxyrinchus","Lamnidae","Lamniformes",445,"Marine","0–500 m",""],
  ["Thresher Shark","Alopias","vulpinus","Alopiidae","Lamniformes",573,"Marine","0–366 m",""],
  ["Wobbegong","Orectolobus","maculatus","Orectolobidae","Orectolobiformes",320,"Marine","0–110 m",""],
  ["Horn Shark","Heterodontus","francisci","Heterodontidae","Heterodontiformes",122,"Marine","2–150 m",""],
  ["Spotted Eagle Ray","Aetobatus","narinari","Aetobatidae","Myliobatiformes",330,"Marine","1–80 m",""],
  ["Southern Stingray","Hypanus","americanus","Dasyatidae","Myliobatiformes",200,"Marine","0–53 m",""],
  ["Electric Ray","Torpedo","torpedo","Torpedinidae","Torpediniformes",60,"Marine","2–400 m","https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Torpedo_torpedo_corsica3.jpg/480px-Torpedo_torpedo_corsica3.jpg"],
  ["Sawfish","Pristis","pristis","Pristidae","Rhinopristiformes",650,"Marine, Freshwater","0–10 m",""],
  ["Yellowtail Clownfish","Amphiprion","clarkii","Pomacentridae","Perciformes",15,"Marine","1–60 m",""],
  ["Banggai Cardinalfish","Pterapogon","kauderni","Apogonidae","Perciformes",8,"Marine","1–5 m",""],
  ["Regal Angelfish","Pygoplites","diacanthus","Pomacanthidae","Perciformes",25,"Marine","1–48 m",""],
  ["Racoon Butterflyfish","Chaetodon","lunula","Chaetodontidae","Perciformes",20,"Marine","1–30 m",""],
  ["Longnose Butterflyfish","Forcipiger","flavissimus","Chaetodontidae","Perciformes",22,"Marine","2–145 m",""],
  ["Six-line Wrasse","Pseudocheilinus","hexataenia","Labridae","Perciformes",10,"Marine","2–35 m",""],
  ["Bicolor Blenny","Ecsenius","bicolor","Blenniidae","Perciformes",11,"Marine","1–25 m",""],
  ["Firefish Goby","Nemateleotris","magnifica","Gobiidae","Gobiiformes",9,"Marine","6–70 m","https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Fire_dartfish_%28Nemateleotris_magnifica%29_%2843372442502%29.jpg/480px-Fire_dartfish_%28Nemateleotris_magnifica%29_%2843372442502%29.jpg"],
  ["Yellow Tang","Zebrasoma","flavescens","Acanthuridae","Perciformes",20,"Marine","2–46 m",""],
  ["Achilles Tang","Acanthurus","achilles","Acanthuridae","Perciformes",24,"Marine","0–4 m",""],
  ["Bluespine Unicornfish","Naso","unicornis","Acanthuridae","Perciformes",70,"Marine","0–80 m",""],
  ["Clown Wrasse","Coris","gaimard","Labridae","Perciformes",40,"Marine","2–50 m",""],
  ["Tomato Clownfish","Amphiprion","frenatus","Pomacentridae","Perciformes",14,"Marine","1–12 m",""],
  ["Green Chromis","Chromis","viridis","Pomacentridae","Perciformes",10,"Marine","1–12 m","https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Blue-green_Chromis%2C_Kiribati_imported_from_iNaturalist_photo_345755248.jpg/480px-Blue-green_Chromis%2C_Kiribati_imported_from_iNaturalist_photo_345755248.jpg"]
];

/* ── Deterministic FNV-1a hash ───────────────────────── */
function fnv(str) {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

function todayKey() {
  const d = new Date();
  return d.getFullYear() + "-" + (d.getMonth() + 1) + "-" + d.getDate();
}

/* ── Pick today's fish and preload image immediately ── */
const FISH_TODAY = FISH[fnv(todayKey()) % FISH.length];
(function(){
  const k = "fotd-img-" + todayKey();
  const u = FISH_TODAY[8] || localStorage.getItem(k);
  if (u) {
    const l = document.createElement("link");
    l.rel = "preload";
    l.as = "image";
    l.fetchPriority = "high";
    l.href = u;
    document.head.appendChild(l);
  }
})();
